# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Nightly Test

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode  
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app && /usr/bin/xcodebuild -version
    # - name: Build
    #   run: xcodebuild build  -scheme SearchOpsTests  -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' 
    - name: Run tests
      run: >
          xcodebuild 
          -scheme SearchOpsTests 
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' 
          -resultBundlePath TestResult/ 
          -enableCodeCoverage YES 
          -derivedDataPath "${RUNNER_TEMP}/Build/DerivedData"
          clean build test 
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
          | xcpretty -r junit && exit ${PIPESTATUS[0]}
    - name: Convert coverage report to sonarqube format
      run: >
          bash ./.github/workflows/xccov-to-sonarqube-generic.sh *.xcresult/ > sonarqube-generic-coverage.xml
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        path: sonarqube-generic-coverage.xml
        retention-days: 1 # Artifact will be available only for 5 days.
  sonar-scan:    
    name: Sonar scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Checkout repository on branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ github.HEAD_REF }}
      #     fetch-depth: 0          
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Run sonar-scanner
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with: 
          args: >
            -Dsonar.projectKey=mccaffers_SearchOps
            -Dsonar.organization=mccaffers
            
    # - name: Setup sonarqube
    #   uses: warchant/setup-sonar-scanner@v3
    # - name: Generate and upload code analysis report
    #   run: >
    #       export PATH=$PATH:$CM_BUILD_DIR/sonar-scanner/bin
    #       sonar-scanner 
    #         -Dsonar.projectKey="mccaffers_SearchOps" 
    #         -Dsonar.organization="mccaffers" 
    #         -Dsonar.host.url="https://sonarcloud.io" 
    #         -Dsonar.login="${{ secrets.SONAR_TOKEN }}" 
    #         -Dsonar.c.file.suffixes=- 
    #         -Dsonar.cpp.file.suffixes=- 
    #         -Dsonar.objc.file.suffixes=- 
    #         -Dsonar.projectVersion=1.0.0 
    #         -Dsonar.sources=. 
    #         -Dsonar.cfamily.build-wrapper-output.bypass=true 
    #         -Dsonar.coverageReportPaths=sonarqube-generic-coverage.xml